### ISSUE TITLE
Trilogy OP codes?

### ISSUE THREAD

**Issue by erfg12** [EQMacEmu/Server#413]
Will the EQ Trilogy OP codes be implemented?

**Comment by SecretsOTheP** [comment]
If proper methods for using the Trilogy client were provided, I don't see why not.

Do you have anything that can be used to launch the Trilogy client under modern OS's? I was having issues digging up the old EQW version that works.

Note we actually have a branch for Trilogy based largely on the work that Harakiri and Yeahlight did over on EQClassic, and I have been wanting to get that working.

**Comment by erfg12** [comment]
If you are doing this on Windows 95, you are done. If you are on Windows XP 
click Compatibility tab > Run this program in compatibility mode for: Windows 95.

That's the only way I have gotten this to work with the EQClassic code given on github.

**Comment by erfg12** [comment]
This will make it work for Windows Vista, 7, 8 etc. No compatibility changes needed, and will put it in a window.

http://www.filedropper.com/eqtrilogyinawindow

**Comment by erfg12** [comment]
Here is a source code that will let you login and get in-game with the Trilogy client if this helps at all. Only real big issue I have with this is NPCs don't seem to spawn, maybe an issue with the NPC_type or spawn2 tables?

SERVER SOURCE: https://drive.google.com/file/d/0B4YtK9YXaHvQamROSUJvN0E1TGM/view
DATABASE: https://drive.google.com/file/d/0B4YtK9YXaHvQRXJnMFg3TW4yamc/view

**Comment by emagi** [comment]
We are looking into getting the Trilogy client working, however this will take some time.

**Comment by erfg12** [comment]
Is it currently working?

**Comment by erfg12** [comment]
http://sourceforge.net/p/dxwnd/discussion/general/thread/0738ee41/

**Comment by emagi** [comment]
Here is Secrets work on fixing the Trilogy client as well: http://www.rerolled.org/showthread.php?6477-The-Al-kabor-Project-%28EQMac%29&p=1278342#post1278342

I am just using eqw 2.32 I haven't had any graphics problems (can run full screen or window), just focus problems which Secrets was looking into.

One thing I did notice though in the Trilogy client is sometimes sound effects like walking seem to linger around in areas long after the NPC is gone pathing through, not sure why this is happening yet.

**Comment by erfg12** [comment]
I was able to login using the Trilogy client with the current Trilogy branch build.

**Comment by emagi** [comment]
Yea it looks like the Trilogy version is passed correctly https://github.com/EQMacEmu/Server/blob/trilogy/loginserver/client.cpp#L166 which is good.  Just noting that changing eqmain.dll then changes the login encryption to eqmac, replacing eqmain.dll had some side effects is all.

Yea, it doesn't look like EQEmu Mac supports VS.Net 2015 at this point, in IRC someone came in the other day concerned about snprintf macro references.  Not sure if it was reported directly to the eqmac team since it was mentioned in the general eqemu channel.

A few of us taking part in the Trilogy project hang out in irc.eqemulator.net, mostly in #eqemucoders - I think we will be using http://www.takproject.net/mantis/login_page.php to track who is working what, but I don't think anyone has set up any tasks yet.
